"""
Hermes Gateway Node WebSocket Server

让手机 App 作为节点客户端连接到 Hermes Gateway，提供硬件能力（摄像头、GPS 等）。
协议与 OpenClaw Node Protocol v3 兼容。

架构:
  Hermes (AI) ←→ node_ws_server (WS Server :nodePort) ←→ App (WS Client)
                                                       ←→ Browser Userscript (WS Client)

配置 (config.yaml):
  node:
    port: 18780
    token: "<auto-generated>"

v2 修复:
  - MCP adapter 改用 request 类型发送 invoke，server 正确路由并返回结果
  - 配对流程修复：配对后断开连接让 App 重连（不再在同一连接等 raw3）
  - 客户端类型识别：App 优先于 Browser 路由命令
  - 支持指定 nodeId 路由 invoke 到特定节点
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import secrets
import sys
import time
from typing import Any

logger = logging.getLogger(__name__)

# ── websockets import (兼容 v11 ~ v14+) ──────────────────────────────────────
# v13+: websockets.asyncio.server.serve, ServerConnection
# v11+: websockets.serve (legacy API)
try:
    import websockets
    _WS_VERSION = tuple(int(x) for x in websockets.__version__.split(".")[:2])
    logger.info(f"websockets version: {websockets.__version__} (parsed: {_WS_VERSION})")

    # Try new API first (v13+)
    try:
        from websockets.asyncio.server import serve as _new_serve, ServerConnection
        _USE_NEW_API = True
        logger.info("Using websockets v13+ asyncio API")
    except ImportError:
        _USE_NEW_API = False
        logger.info("Using websockets legacy API")
except ImportError:
    websockets = None  # type: ignore
    _USE_NEW_API = False
    _WS_VERSION = (0, 0)


def _check_websockets():
    """Ensure websockets is available."""
    if websockets is None:
        print(
            "ERROR: 'websockets' package is required for node_ws_server.\n"
            "Install: /root/.hermes/hermes-agent/venv/bin/pip install websockets",
            file=sys.stderr,
        )
        sys.exit(1)


class ConnectedNode:
    """A connected node (phone app or browser)."""

    def __init__(self, ws: Any, device_id: str, commands: list[str],
                 caps: list[str], client_type: str = "app"):
        self.ws = ws
        self.device_id = device_id
        self.commands = commands
        self.caps = caps
        self.client_type = client_type  # "app" | "browser" | "mcp"
        self.connected_at = time.time()
        self.pending_invokes: dict[str, asyncio.Future] = {}

    def has_command(self, command: str) -> bool:
        return command in self.commands


class NodeWsServer:
    """
    WebSocket server that accepts node (phone app) connections.

    Protocol (OpenClaw Node Protocol v3 compatible):
      1. Server → Client: event "connect.challenge" {nonce}
      2. Client → Server: request "connect" {device, commands, caps, auth}
      3. Server → Client: response {ok: true, auth: {deviceToken}}
      4. Server → Client: event "node.invoke.request" {id, command, paramsJSON}
      5. Client → Server: request "node.invoke.result" {id, ok, payloadJSON}
    """

    def __init__(self, auth_token: str, port: int = 18780):
        if websockets is None:
            raise ImportError("websockets package is required. Install: pip install websockets")

        self._auth_token = auth_token
        self._port = port
        self._server = None
        self._nodes: dict[str, ConnectedNode] = {}  # device_id → ConnectedNode
        self._ws_to_device: dict[Any, str] = {}  # ws → device_id
        self._device_tokens: dict[str, str] = {}  # device_id → device_token
        self._invoke_counter = 0
        self._pending_invokes: dict[str, asyncio.Future] = {}  # invoke_id → Future
        self._loop: asyncio.AbstractEventLoop | None = None
        self._serve_ctx: Any = None  # async context manager reference for stop()
        self._ready = False  # True once server is accepting connections

    @property
    def connected_nodes(self) -> dict[str, ConnectedNode]:
        return dict(self._nodes)

    @property
    def all_commands(self) -> list[str]:
        commands = set()
        for node in self._nodes.values():
            commands.update(node.commands)
        return sorted(commands)

    @property
    def is_ready(self) -> bool:
        return self._ready

    async def start(self):
        """Start the WebSocket server."""
        self._loop = asyncio.get_event_loop()

        if _USE_NEW_API:
            # websockets v13+: use asyncio API with async context manager
            serve_obj = _new_serve(
                self._handle_connection,
                "0.0.0.0",
                self._port,
                ping_interval=30,
                ping_timeout=10,
            )
            # Try entering the async context manager (v16+)
            try:
                self._server = await serve_obj.__aenter__()
                self._serve_ctx = serve_obj  # keep reference for __aexit__
                logger.info(
                    f"Node WS server listening on 0.0.0.0:{self._port} "
                    f"(async context manager, websockets {websockets.__version__})"
                )
            except AttributeError:
                # Older websockets v13-15: serve() is directly awaitable
                self._server = await serve_obj
                self._serve_ctx = None
                logger.info(
                    f"Node WS server listening on 0.0.0.0:{self._port} "
                    f"(awaitable, websockets {websockets.__version__})"
                )
        else:
            # websockets v11-12: legacy API
            self._server = await websockets.serve(
                self._handle_connection,
                "0.0.0.0",
                self._port,
                ping_interval=30,
                ping_timeout=10,
            )
            self._serve_ctx = None
            logger.info(
                f"Node WS server listening on 0.0.0.0:{self._port} "
                f"(legacy API, websockets {websockets.__version__})"
            )

        self._ready = True

    async def stop(self):
        """Stop the WebSocket server."""
        self._ready = False
        if self._serve_ctx is not None:
            try:
                await self._serve_ctx.__aexit__(None, None, None)
            except Exception:
                pass
            self._serve_ctx = None
        elif self._server:
            self._server.close()
            await self._server.wait_closed()
        self._server = None

    def _detect_client_type(self, payload: dict) -> str:
        """Detect client type from connect payload."""
        client_info = payload.get("client", {})
        platform = client_info.get("platform", "")
        device_info = payload.get("device", {})
        device_id = device_info.get("id", "")

        if platform == "browser" or device_id.startswith("browser-"):
            return "browser"
        if platform == "mcp":
            return "mcp"
        return "app"

    async def _handle_connection(self, ws: Any):
        """Handle a new WebSocket connection from a node app."""
        device_id = None
        remote = getattr(ws, 'remote_address', 'unknown')
        try:
            # Step 1: Send challenge
            nonce = secrets.token_hex(16)
            challenge_frame = json.dumps({
                "type": "event",
                "event": "connect.challenge",
                "payload": {"nonce": nonce},
            })
            await ws.send(challenge_frame)
            logger.info(f"[WS] [{remote}] Step 1: challenge sent")

            # Step 2: Wait for connect request
            logger.info(f"[WS] [{remote}] Step 2: waiting for connect request...")
            raw = await asyncio.wait_for(ws.recv(), timeout=30)
            logger.info(f"[WS] [{remote}] Step 2: received {len(raw)} bytes")
            frame = json.loads(raw)
            logger.info(
                f"[WS] [{remote}] Step 2: frame type={frame.get('type')}, "
                f"method/request={frame.get('method') or frame.get('request')}"
            )

            # Accept both protocol formats:
            #   App sends: {"type": "req", "method": "connect", "params": {...}}
            #   Standard:  {"type": "request", "request": "connect", "payload": {...}}
            frame_type = frame.get("type")
            frame_request = frame.get("request") or frame.get("method")
            if frame_type not in ("request", "req") or frame_request != "connect":
                logger.warning(
                    f"[WS] [{remote}] REJECTED: type={frame_type}, request={frame_request}"
                )
                await ws.send(json.dumps({
                    "type": "res",
                    "id": frame.get("id", ""),
                    "ok": False,
                    "error": {
                        "code": "INVALID_REQUEST",
                        "message": f"Expected connect, got type={frame_type} req={frame_request}",
                    },
                }))
                return

            # Accept payload from either "payload" or "params" field
            payload = frame.get("payload") or frame.get("params") or {}
            device_info = payload.get("device", {})
            device_id = device_info.get("id", "unknown")
            commands = payload.get("commands", [])
            caps = payload.get("caps", [])
            client_type = self._detect_client_type(payload)
            logger.info(
                f"[WS] [{remote}] Step 2: device={device_id}, type={client_type}, "
                f"cmds={len(commands)}"
            )

            # Verify auth token
            # Browser clients skip token validation — they have no token mechanism.
            # App/MCP clients must provide a valid token if auth_token is configured.
            auth = payload.get("auth", {})
            token = auth.get("token", "")
            token_valid = (
                client_type == "browser"  # ★ 浏览器免验证
                or token == self._auth_token
                or (device_id in self._device_tokens and token == self._device_tokens[device_id])
            )
            logger.info(f"[WS] [{remote}] Step 2: token_valid={token_valid} (type={client_type})")

            if not token_valid and self._auth_token:
                logger.info(f"[WS] [{remote}] Step 2: TOKEN_INVALID, entering pairing flow")
                await ws.send(json.dumps({
                    "type": "res",
                    "id": frame.get("id", ""),
                    "ok": False,
                    "error": {"code": "TOKEN_INVALID", "message": "Invalid auth token"},
                }))
                # Fix pairing flow: handle pair request, then exit.
                # App will disconnect and reconnect with the new device token.
                await self._handle_pairing(ws, device_id, remote)
                return

            # Step 3: Register node & send connect response
            await self._register_node(ws, device_id, commands, caps, client_type, frame, remote)

        except asyncio.TimeoutError:
            logger.warning(f"[WS] [{remote}] Timeout waiting for message")
        except websockets.exceptions.ConnectionClosed as e:
            logger.info(f"[WS] [{remote}] Connection closed: {e}")
        except Exception as e:
            logger.warning(f"[WS] [{remote}] Error: {type(e).__name__}: {e}")
        finally:
            if device_id and device_id in self._nodes:
                del self._nodes[device_id]
                if id(ws) in self._ws_to_device:
                    del self._ws_to_device[id(ws)]
                # ★ 节点断开时，清理所有指向该节点的 pending invokes
                self._reject_pending_invokes_for_node(device_id)
                logger.info(f"[WS] [{remote}] Node removed: {device_id}")

    async def _handle_pairing(self, ws: Any, device_id: str, remote: str):
        """Handle pairing flow after TOKEN_INVALID.

        Fix: App disconnects and reconnects after receiving pairing approval,
        so we don't wait for raw3 on the same connection. We just handle the
        pair request, send approval, and return. The connection loop will end
        naturally when App disconnects.
        """
        try:
            raw2 = await asyncio.wait_for(ws.recv(), timeout=60)
            frame2 = json.loads(raw2)
            frame2_request = frame2.get("request") or frame2.get("method")
            logger.info(f"[WS] [{remote}] Pairing: received request={frame2_request}")

            if frame2_request == "node.pair.request":
                device_token = secrets.token_hex(16)
                self._device_tokens[device_id] = device_token
                await ws.send(json.dumps({
                    "type": "res",
                    "id": frame2.get("id", ""),
                    "ok": True,
                    "payload": {"code": "APPROVED", "auth": {"deviceToken": device_token}},
                }))
                logger.info(
                    f"[WS] [{remote}] Pairing APPROVED for {device_id}, "
                    f"token issued. App should disconnect and reconnect."
                )
                # Don't wait for raw3 — App will disconnect and reconnect
                # with the new device token. Let the connection close naturally.
            else:
                logger.warning(
                    f"[WS] [{remote}] Pairing: expected node.pair.request, "
                    f"got {frame2_request}"
                )
        except asyncio.TimeoutError:
            logger.warning(f"[WS] [{remote}] Pairing timeout")

    async def _register_node(self, ws: Any, device_id: str, commands: list[str],
                              caps: list[str], client_type: str,
                              connect_frame: dict, remote: str):
        """Register a connected node and enter the message loop."""
        if device_id not in self._device_tokens:
            self._device_tokens[device_id] = secrets.token_hex(16)

        node = ConnectedNode(ws, device_id, commands, caps, client_type)
        self._nodes[device_id] = node
        self._ws_to_device[id(ws)] = device_id

        await ws.send(json.dumps({
            "type": "res",
            "id": connect_frame.get("id", ""),
            "ok": True,
            "payload": {"auth": {"deviceToken": self._device_tokens[device_id]}},
        }))
        logger.info(
            f"[WS] [{remote}] CONNECTED device={device_id} type={client_type} "
            f"cmds={commands}"
        )

        # Step 4: Listen for messages
        async for raw in ws:
            try:
                msg = json.loads(raw)
                await self._on_message(device_id, msg)
            except json.JSONDecodeError:
                pass
        logger.info(f"[WS] [{remote}] Step 4: message loop ended")

    async def _on_message(self, device_id: str, msg: dict):
        """Handle a message from a connected node."""
        msg_type = msg.get("type")

        # ── Handle events ──
        if msg_type == "event":
            event_name = msg.get("event")
            payload = msg.get("payload") or {}

            if event_name == "node.capabilities":
                node = self._nodes.get(device_id)
                if node:
                    node.commands = payload.get("commands", payload.get("capabilities", []))
                    node.caps = payload.get("caps", [])
                    logger.info(f"Node {device_id} updated commands: {len(node.commands)} cmds")

            elif event_name == "node.invoke.request":
                # ── 修复：正确路由来自其他节点的 invoke 请求 ──
                command = payload.get("command", "")
                params_raw = payload.get("paramsJSON", "{}")
                params = json.loads(params_raw) if isinstance(params_raw, str) else params_raw
                invoke_id = payload.get("id", "")
                target_node_id = payload.get("nodeId")

                logger.info(f"[WS] [{device_id}] event invoke: {command} (id={invoke_id})")

                # Find target node
                target_node = self._find_target_node(command, target_node_id, device_id)
                if target_node is None:
                    logger.warning(f"[WS] [{device_id}] No node for command: {command}")
                    if invoke_id:
                        await self._send_to_node(device_id, {
                            "type": "res",
                            "id": invoke_id,
                            "ok": False,
                            "error": {"message": f"No node supports: {command}"},
                        })
                    return

                # Create pending invoke and forward to target
                if self._loop is None:
                    return
                future: asyncio.Future[dict[str, Any]] = self._loop.create_future()
                self._pending_invokes[invoke_id] = future

                await target_node.ws.send(json.dumps({
                    "type": "event",
                    "event": "node.invoke.request",
                    "payload": {
                        "id": invoke_id,
                        "nodeId": target_node.device_id,
                        "command": command,
                        "paramsJSON": json.dumps(params or {}),
                        "timeoutMs": payload.get("timeoutMs", 30000),
                    },
                }))
                logger.info(
                    f"[WS] [{device_id}] forwarded invoke {command} "
                    f"→ {target_node.device_id} (pending={invoke_id})"
                )

                # Wait for result and send back to requester
                try:
                    timeout_s = (payload.get("timeoutMs", 30000)) / 1000.0
                    result = await asyncio.wait_for(future, timeout=timeout_s)
                    ok = result.get("ok", True)
                    await self._send_to_node(device_id, {
                        "type": "res",
                        "id": invoke_id,
                        "ok": ok,
                        "payload": result if ok else None,
                        "error": result.get("error") if not ok else None,
                    })
                except asyncio.TimeoutError:
                    self._pending_invokes.pop(invoke_id, None)
                    await self._send_to_node(device_id, {
                        "type": "res",
                        "id": invoke_id,
                        "ok": False,
                        "error": {"message": f"Invoke timed out: {command}"},
                    })
                except Exception as e:
                    self._pending_invokes.pop(invoke_id, None)
                    await self._send_to_node(device_id, {
                        "type": "res",
                        "id": invoke_id,
                        "ok": False,
                        "error": {"message": str(e)},
                    })
            return

        # ── Handle requests ──
        if msg_type in ("request", "req"):
            request_name = msg.get("request") or msg.get("method")
            request_id = msg.get("id")
            payload = msg.get("payload") or msg.get("params") or {}

            if request_name == "node.invoke.result":
                invoke_id = payload.get("id")
                if invoke_id and invoke_id in self._pending_invokes:
                    future = self._pending_invokes.pop(invoke_id)
                    if not future.done():
                        future.set_result(payload)
                # ★ Send ack back to App (it uses sendRequest and expects a response)
                if request_id:
                    await self._send_to_node(device_id, {
                        "type": "res",
                        "id": request_id,
                        "ok": True,
                        "payload": {},
                    })
                return

            if request_name == "node.capabilities":
                node = self._nodes.get(device_id)
                if node:
                    node.commands = payload.get("commands", payload.get("capabilities", []))
                    node.caps = payload.get("caps", [])
                    logger.info(f"Node {device_id} updated commands: {len(node.commands)} cmds")
                # Ack
                if request_id:
                    await self._send_to_node(device_id, {
                        "type": "res",
                        "id": request_id,
                        "ok": True,
                        "payload": {},
                    })
                return

            # ── Fix: handle node.invoke.request as request (from MCP adapter) ──
            # MCP adapter sends "node.invoke.request" as a request type,
            # expecting a response with the invoke result.
            if request_name == "node.invoke.request":
                command = payload.get("command", "")
                params_raw = payload.get("paramsJSON", "{}")
                params = json.loads(params_raw) if isinstance(params_raw, str) else params_raw
                invoke_id = payload.get("id", "")
                target_node_id = payload.get("nodeId")

                logger.info(
                    f"[WS] [{device_id}] request invoke: {command} "
                    f"(id={invoke_id}, target={target_node_id})"
                )

                # Find target node
                target_node = self._find_target_node(command, target_node_id, device_id)
                if target_node is None:
                    if request_id:
                        await self._send_to_node(device_id, {
                            "type": "res",
                            "id": request_id,
                            "ok": False,
                            "error": {
                                "code": "NO_NODE",
                                "message": f"No connected node supports command: {command}",
                            },
                        })
                    return

                # Create pending invoke and forward to target
                if self._loop is None:
                    return
                future: asyncio.Future[dict[str, Any]] = self._loop.create_future()
                self._pending_invokes[invoke_id] = future

                await target_node.ws.send(json.dumps({
                    "type": "event",
                    "event": "node.invoke.request",
                    "payload": {
                        "id": invoke_id,
                        "nodeId": target_node.device_id,
                        "command": command,
                        "paramsJSON": json.dumps(params or {}),
                        "timeoutMs": payload.get("timeoutMs", 30000),
                    },
                }))
                logger.info(
                    f"[WS] [{device_id}] routed invoke {command} "
                    f"→ {target_node.device_id} (pending={invoke_id})"
                )

                # Wait for result
                try:
                    timeout_s = (payload.get("timeoutMs", 30000)) / 1000.0
                    result = await asyncio.wait_for(future, timeout=timeout_s)
                    ok = result.get("ok", True)
                    # Return result as response to the original request
                    if request_id:
                        await self._send_to_node(device_id, {
                            "type": "res",
                            "id": request_id,
                            "ok": ok,
                            "payload": result if ok else None,
                            "error": result.get("error") if not ok else None,
                        })
                except asyncio.TimeoutError:
                    self._pending_invokes.pop(invoke_id, None)
                    if request_id:
                        await self._send_to_node(device_id, {
                            "type": "res",
                            "id": request_id,
                            "ok": False,
                            "error": {
                                "code": "TIMEOUT",
                                "message": f"Invoke timed out: {command}",
                            },
                        })
                except Exception as e:
                    self._pending_invokes.pop(invoke_id, None)
                    if request_id:
                        await self._send_to_node(device_id, {
                            "type": "res",
                            "id": request_id,
                            "ok": False,
                            "error": {"code": "INVOKE_ERROR", "message": str(e)},
                        })
                return

    # JS/Browser 专属命令 — 这些命令应该优先发给 browser 节点（直接执行），
    # 而不是 app 节点（app 只是转发给 JsBridgeServer，效率更低）
    _JS_COMMANDS = frozenset({
        'accessibility.js_exec',
        'accessibility.js_bridge_info',
        'canvas.eval',
        'canvas.navigate',
        'canvas.snapshot',
    })

    def _find_target_node(
        self,
        command: str,
        target_node_id: str | None,
        requester_device_id: str,
    ) -> ConnectedNode | None:
        """Find the best target node for an invoke command.

        Priority:
          1. If target_node_id specified and exists, use it
          2. For JS commands: prefer "browser" > "app" (browser executes directly)
          3. For native commands: prefer "app" > "browser" (app has native access)
          4. Among same client type, prefer the node that isn't the requester
        """
        # If specific target requested
        if target_node_id and target_node_id != "*":
            node = self._nodes.get(target_node_id)
            if node and node.has_command(command):
                return node
            # Fall through to general search

        # Find all nodes that support this command (excluding requester)
        candidates = [
            n for n in self._nodes.values()
            if n.has_command(command) and n.device_id != requester_device_id
        ]

        if not candidates:
            # Include requester as last resort (for self-invoke)
            candidates = [
                n for n in self._nodes.values() if n.has_command(command)
            ]

        if not candidates:
            return None

        # JS 命令优先 browser（直接执行），native 命令优先 app
        if command in self._JS_COMMANDS:
            # browser > mcp > app
            type_priority = {"browser": 0, "mcp": 1, "app": 2}
        else:
            # app > mcp > browser
            type_priority = {"app": 0, "mcp": 1, "browser": 2}

        candidates.sort(key=lambda n: type_priority.get(n.client_type, 99))
        best = candidates[0]
        logger.info(
            f"[ROUTE] {command} → {best.device_id} "
            f"(type={best.client_type}, candidates="
            f"{[(c.device_id, c.client_type) for c in candidates]})"
        )
        return best

    async def _send_to_node(self, device_id: str, frame: dict):
        """Send a JSON frame to a connected node by device_id."""
        node = self._nodes.get(device_id)
        if node and node.ws:
            try:
                await node.ws.send(json.dumps(frame))
            except Exception as e:
                logger.warning(f"[WS] Failed to send to {device_id}: {e}")

    def _reject_pending_invokes_for_node(self, device_id: str):
        """Reject all pending invokes that target a disconnected node."""
        to_reject = []
        for invoke_id, future in self._pending_invokes.items():
            if not future.done():
                # We can't easily check which node this invoke targeted,
                # so we reject all undelivered invokes. This is safe because
                # invoke_command() has its own timeout as a fallback.
                to_reject.append(invoke_id)

        for invoke_id in to_reject:
            future = self._pending_invokes.pop(invoke_id, None)
            if future and not future.done():
                future.set_exception(
                    RuntimeError(f"Node {device_id} disconnected")
                )
                logger.info(f"[WS] Rejected pending invoke {invoke_id} (node disconnected)")

    async def invoke_command(
        self,
        command: str,
        params: dict[str, Any] | None = None,
        timeout: float = 30.0,
    ) -> dict[str, Any]:
        if self._loop is None:
            raise RuntimeError("Server not started")

        node = self._find_target_node(command, None, "")
        if node is None:
            raise RuntimeError(f"No connected node supports command: {command}")

        self._invoke_counter += 1
        invoke_id = f"inv-{self._invoke_counter}-{secrets.token_hex(4)}"

        future: asyncio.Future[dict[str, Any]] = self._loop.create_future()
        self._pending_invokes[invoke_id] = future

        await node.ws.send(json.dumps({
            "type": "event",
            "event": "node.invoke.request",
            "payload": {
                "id": invoke_id,
                "nodeId": node.device_id,
                "command": command,
                "paramsJSON": json.dumps(params or {}),
                "timeoutMs": int(timeout * 1000),
            },
        }))

        try:
            result = await asyncio.wait_for(future, timeout=timeout)
            if result.get("ok") is False:
                error = result.get("error", {})
                raise RuntimeError(f"Command failed: {error.get('message', 'unknown error')}")
            # 提取实际结果，剥离 App 的 metadata (id, nodeId 等)
            payload_json = result.get("payloadJSON")
            if payload_json:
                return json.loads(payload_json)
            return {k: v for k, v in result.items() if k not in ("id", "nodeId", "ok")}
        except asyncio.TimeoutError:
            self._pending_invokes.pop(invoke_id, None)
            raise RuntimeError(f"Command timed out after {timeout}s: {command}")


async def main():
    """Main entry point for the node WS server."""
    _check_websockets()

    port = int(os.getenv("NODE_WS_PORT", "18780"))
    token = os.getenv("NODE_AUTH_TOKEN", "")

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )
    logger.info(
        f"Starting Node WS Server on port {port} "
        f"(websockets version: {websockets.__version__})"
    )

    server = NodeWsServer(auth_token=token, port=port)
    await server.start()
    logger.info(f"Node WS Server is ready on 0.0.0.0:{port}")

    # Write a marker file so the Flutter app and MCP adapter can detect readiness.
    # Include port and PID for diagnostics.
    try:
        with open("/tmp/node_ws_server.ready", "w") as f:
            f.write(json.dumps({
                "port": port,
                "pid": os.getpid(),
                "started_at": time.time(),
                "websockets_version": websockets.__version__,
            }))
    except Exception:
        pass

    try:
        await asyncio.Future()  # run forever
    except (KeyboardInterrupt, asyncio.CancelledError):
        logger.info("Shutting down Node WS Server...")
    finally:
        await server.stop()
        # Clean up marker file
        try:
            os.unlink("/tmp/node_ws_server.ready")
        except Exception:
            pass


if __name__ == "__main__":
    asyncio.run(main())
